version: "3.8"

services:
  hr_bot:
    build: .
    container_name: hr_bot
    restart: always
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
    - ./bot_data.db:/bot_data.db
    networks:
      - bot_network

  redis:
    image: redis:7
    container_name: hr_bot_redis
    restart: always
    networks:
      - bot_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sqlite_data:

networks:
  bot_network:
    driver: bridge
